### ISSUE TITLE
Older MacOS Support

### ISSUE THREAD

**Issue by exiva** [onmyway133/GifCapture#1]
Can support for older releases of macOS (10.11 specifically) be added in a future release?

**Comment by onmyway133** [comment]
@exiva thanks, there's no reason not to support older macOS versions. I will lower the requirement version

**Comment by onmyway133** [comment]
@exiva thanks, I update to support 10.11 in this release https://github.com/onmyway133/GifCapture/releases/tag/1.0.3

Due to `LayoutAnchor`, I can't lower it more
