### ISSUE TITLE
Support Caskroom

### ISSUE THREAD

**Issue by natalia-osa** [onmyway133/GifCapture#2]
Please add the support for the caskrooom, which lets the user manage the versions etc painlessly: https://caskroom.github.io (docs to add a new cask: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md).

**Comment by onmyway133** [comment]
@natalia-osa Hi, long time no see. Thanks for your suggestion. I will read caskroom and see if I can support it 👍

**Comment by natalia-osa** [comment]
Fantastic. Great work by the way (grats on swift #1 trending), happy to see you're still so active!

**Comment by onmyway133** [comment]
@natalia-osa Hi, I made the PR here https://github.com/caskroom/homebrew-cask/pull/30685, hope it will be merged soon

**Comment by natalia-osa** [comment]
Great, waiting forward to install it this way, don't forget to let me know it's available please :)

**Comment by onmyway133** [comment]
@natalia-osa Hi, it is merged now. I think you can use `brew cask` now. Have a nice weekend
