### ISSUE TITLE
cannot install with brew cask

### ISSUE THREAD

**Issue by futurist** [onmyway133/GifCapture#6]
```
mac:~ pro$ brew cask install gifcapture
Error: No available Cask for gifcapture
Error: nothing to install
```

**Comment by onmyway133** [comment]
@futurist Hi, I have the brew cask definition here https://github.com/caskroom/homebrew-cask/pull/30685/files, but don't know why you can't install it. In the mean time you can download it from releases https://github.com/onmyway133/GifCapture/releases

If you can make a PR to fix this, it would be more than great
