### ISSUE TITLE
have a options to generate endless loop gif?

### ISSUE THREAD

**Issue by axetroy** [onmyway133/GifCapture#7]
sometimes, we need endless loop gif.

But the GifCapture only generate the gif which ``loop = 1``

I have to use another tool to transform it to endless loop

**Comment by onmyway133** [comment]
@axetroy Hi, which version of GifCapture do you use? From https://github.com/onmyway133/GifCapture/releases/tag/1.0.2 I fixed the gif not being able to loop

**Comment by axetroy** [comment]
@onmyway133 
I am using ``1.1.0 (1)``

That's my problem.

after generating gif, I edit it with Mac OS build-in ``Image Preview`` application.

so it loses loop param.

Thanks for your help.

**Comment by onmyway133** [comment]
@axetroy Glad you solved it 👍 Thanks for using GifCapture ❤️
